# The slash workflow handles slash commands
#
# Slash commands are given through comments on pull requests
# and may be used only by individuals with "write" access to
# the repository (i.e. maintainers).
#
# The workflow looks dispatches another workflow named <command>-command
# which must exist in the repository.
#
# Supported commands:
# - /land: invokes the land-command workflow, to land (merge) PRs
#          stacked through ghstack

name: Slash Command Routing
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - name: route-land
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.LAND_TOKEN }}
        reaction-token: ${{ secrets.LAND_TOKEN }}
        issue-type: pull-request
        permission: write
        commands: |
          land
