# The slash workflow handles slash commands
#
# Slash commands are given through comments on pull requests
# and may be used only by individuals with "write" access to
# the repository (i.e. maintainers).
#
# Slash commands must be placed at the very beginning of the
# first line of a comment. More details are available in the
# action docs: https://github.com/peter-evans/slash-command-dispatch/tree/main?tab=readme-ov-file#how-comments-are-parsed-for-slash-commands
#
# The workflow looks for and dispatches to another workflow
# named <command>-command which must exist in the repository.
#
# Supported commands:
# - /land: invokes the land-command workflow, to land (merge) PRs
#          stacked through ghstack
#
# When a command is recognised, the rocket and eyes emojis are added
# When a command is executed successfully, the horray emoji is added
# When a command execution fails, a comment is added with a link to the logs

name: Slash Command Routing
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - name: route-land
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.LAND_TOKEN }}
        reaction-token: ${{ secrets.LAND_TOKEN }}
        issue-type: pull-request
        permission: write
        commands: |
          land

    - name: Create URL to the run output
      if: ${{ failure() }}
      id: vars
      run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
  
    - name: Create comment
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.LAND_TOKEN }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
          Something went wrong with your `/${{ github.event.client_payload.slash_command.command }}` command: [please check the logs][1].

          [1]: ${{ steps.vars.outputs.run-url }}

    - name: Add reaction
      if: ${{ success() }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.LAND_TOKEN }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reaction-type: hooray